### ISSUE TITLE
Events for drawEnd and drawBegin

### ISSUE THREAD

**Issue by theawless** [leader22/simple-drawing-board.js#20]
One use case for drawEnd can be to send the image over to a server. The draw event is triggered many times during one stroke and hence we can't call the server using it. On the other hand, the drawEnd event will only happen at the end of a stroke.

I will be able to contribute for this change, do you think this feature is a good idea?

**Comment by leader22** [comment]
Thank you for opening issues!(also #21 )

But since I did not work on this repo through a few years, I can't answer right now.
I'm going to investigate my old codes 🙄and I think I can answer you tomorrow.

**Comment by leader22** [comment]
sorry for the delay in responding.

I added `drawBegin` and `drawEnd` events in version `2.1.0` 😉
