### ISSUE TITLE
fillImageByDataURL not support overlay

### ISSUE THREAD

**Issue by Darcrandex** [leader22/simple-drawing-board.js#26]
at 2.x, api "setImg" can use option "overlay". but at 3.x, "fillImageByDataURL" not support.
will you fix it?

**Comment by leader22** [comment]
Thank you for your feedback 😃 

I've just added the same option now and published as `v3.1.1`.
Would you please try it?

**Comment by Darcrandex** [comment]
> 感谢您的反馈意见 😃
> 
> 我刚刚添加了相同的选项，并发布为`v3.1.1`。
> 你可以试试看吗？

ok, thank you.
