### ISSUE TITLE
Question about eraser tool!

### ISSUE THREAD

**Issue by dogrocker** [leader22/simple-drawing-board.js#28]
Hello! Thank for modern library.

May you implement Eraser tool ?

And I have question about, How to resizing window with `fillImageByElement()`
Because I use `addEventListener('resize)` and set.

```
sdb.canvas.width = this.windowWidth
sdb.canvas.height = this.windowHeight
sdb.fillImageByElement(document.getElementById('img'))
``` 

It work but not recreate the draw line.

My need is canvas can resize to any size, But when save the image it should generate with fixed size ~(800x800px).

Thanks for any suggestion.

**Comment by leader22** [comment]
Hi 😺 

> May you implement Eraser tool ?

We already have `toggleMode()`.

```js
// switch DRAW <=> ERASE
sdb.mode; // "draw"

sdb.toggleMode();
sdb.mode; // "erase"
```

Does this match for you?

> How to resizing window with fillImageByElement()

You mean "pasted image should be the same size before and after canvas resizing"?

The **fill**ImageXxx() is the API that - literally - fills whole canvas with given image. So it does not intend to keep image size.

**Comment by dogrocker** [comment]
@leader22 . Thanks for answer, My eyes is blind.

For question 2.
I mean I used this libs for pc canvas size is 1024x1024 and mobile size is 500x500 when user drawing on image (`fillImageByElement()`) then click save with `toDataURL()` I need solution for resize the drawing path in to 800x800

**Comment by leader22** [comment]
Ok, I understand your needs 🕵️ 

---

Reproducing steps are

- Create canvas w/ actual size (e.g.`1024x1024`)
- Setup `sdb`
- Call `fillImageXxx()`
- Draw some lines
- Resize it by assigning new `canvas.width/height`
  - change actual size

At this time, image and drawings disappear! How to keep them after resizing?

---

Canvas context is cleared(= reset) on resize.
This is defined in the DOM spec(https://html.spec.whatwg.org/multipage/canvas.html#reset-the-rendering-context-to-its-default-state).

- So you must save them before resizing
  - by `toDataURL()`
- And restore it after resizing
  - by `fillImageByDataURL()`
  - it may blur on scale up

or 

- Do not resize canvas context
- Instead, use CSS and scale up/down
  - change `canvas.style`, `.width` or `transform: scale` does not clear the context
  - note that original image size are not changed

How is it?
